"""Shared helpers for constructing and appending evidence entries."""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import TYPE_CHECKING, Any

from app.agent.state import update_state

if TYPE_CHECKING:
    from app.agent.state import InvestigationState


@dataclass(frozen=True)
class EvidenceEntry:
    """Single evidence record generated by a tool."""

    category: str
    tool: str
    description: str
    data: dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> dict[str, Any]:
        """Convert the dataclass to persisted evidence payload shape."""
        return {
            "category": self.category,
            "tool": self.tool,
            "description": self.description,
            "data": self.data,
        }


def append_evidence(
    state: InvestigationState,
    entry: EvidenceEntry,
    **updates: Any,
) -> InvestigationState:
    """Append one evidence entry while applying additional state updates."""
    return update_state(state, evidence=[*state["evidence"], entry.to_dict()], **updates)
