"""Render a lightweight summary HTML report from matrix JSON output.

Note: this is a compact summary renderer. The detailed, stage-by-stage report is
generated by `scripts/run_e2e_matrix_detailed.py` into
`htmlcov/e2e-scenarios-report.html`.
"""

from __future__ import annotations

import argparse
import html
import json
from pathlib import Path
from typing import Any


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Render E2E matrix JSON as an HTML report.")
    parser.add_argument(
        "--input",
        default="htmlcov/e2e-31-matrix-report-after-docker-fix.json",
        help="Path to matrix JSON report.",
    )
    parser.add_argument(
        "--output",
        default="htmlcov/e2e-scenarios-summary.html",
        help="Path to output HTML file.",
    )
    return parser.parse_args()


def _render_summary(report: dict[str, Any]) -> str:
    generated_at = html.escape(str(report.get("generated_at", "")))
    scenario_count = html.escape(str(report.get("scenario_count", 0)))
    issue_counts = report.get("issue_counts", {})
    latency = report.get("latency_ms", {})
    return (
        "<div class='summary'>"
        f"<p><strong>Generated:</strong> {generated_at}</p>"
        f"<p><strong>Scenario count:</strong> {scenario_count}</p>"
        f"<p><strong>Latency:</strong> run_p95={html.escape(str(latency.get('run_p95', 'n/a')))} ms, "
        f"detail_p95={html.escape(str(latency.get('detail_p95', 'n/a')))} ms</p>"
        f"<p><strong>Issue counts:</strong> {html.escape(json.dumps(issue_counts, sort_keys=True))}</p>"
        "</div>"
    )


def _render_rows(report: dict[str, Any]) -> str:
    rows = report.get("rows", [])
    if not isinstance(rows, list):
        rows = []

    body = []
    for row in rows:
        if not isinstance(row, dict):
            continue
        issues = row.get("issues", [])
        if isinstance(issues, list):
            issues_text = ", ".join(str(i) for i in issues)
        else:
            issues_text = str(issues)
        body.append(
            "<tr>"
            f"<td>{html.escape(str(row.get('scenario', '')))}</td>"
            f"<td>{html.escape(str(row.get('bucket', '')))}</td>"
            f"<td>{html.escape(str(row.get('status', '')))}</td>"
            f"<td>{html.escape(str(row.get('severity', '')))}</td>"
            f"<td>{html.escape(str(row.get('recommendation_count', 0)))}</td>"
            f"<td>{html.escape(str(row.get('evidence_count', 0)))}</td>"
            f"<td>{html.escape(str(row.get('run_latency_ms', '')))}</td>"
            f"<td>{html.escape(str(row.get('detail_latency_ms', '')))}</td>"
            f"<td>{html.escape(issues_text)}</td>"
            "</tr>"
        )

    return (
        "<table>"
        "<thead><tr>"
        "<th>Scenario</th><th>Bucket</th><th>Status</th><th>Severity</th>"
        "<th>Recs</th><th>Evidence</th><th>Run ms</th><th>Detail ms</th><th>Issues</th>"
        "</tr></thead>"
        f"<tbody>{''.join(body)}</tbody>"
        "</table>"
    )


def main() -> int:
    args = _parse_args()
    input_path = Path(args.input)
    output_path = Path(args.output)

    report = json.loads(input_path.read_text(encoding="utf-8"))
    title = "E2E Scenarios Summary (Compact)"

    html_doc = (
        "<!doctype html><html><head><meta charset='utf-8'>"
        f"<title>{title}</title>"
        "<style>"
        "body{font-family:Segoe UI,Arial,sans-serif;margin:24px;line-height:1.4}"
        "table{border-collapse:collapse;width:100%;font-size:13px}"
        "th,td{border:1px solid #d0d0d0;padding:6px;vertical-align:top;text-align:left}"
        "th{background:#f2f2f2;position:sticky;top:0}"
        ".summary{background:#fafafa;border:1px solid #ddd;padding:12px;margin-bottom:16px}"
        "</style></head><body>"
        f"<h1>{title}</h1>"
        f"{_render_summary(report)}"
        f"{_render_rows(report)}"
        "</body></html>"
    )

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(html_doc, encoding="utf-8")
    print(f"Rendered HTML report: {output_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
